name: Deploy GitHub Pages

on:
  push:
    branches: ["main"] # Mude para "master" se sua branch principal tiver esse nome

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Renomear arquivo para index na publicação
        run: cp CalculoFreteNota.html index.html

      - name: Configurar Pages
        uses: actions/configure-pages@v4

      - name: Upload artefato
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy para GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
